ovro-eovsa/ovro-lwa-solar

- ovro_lwa_solar_cal.py
I have added a function which shall flag the bad antennas. The routine used to find out the bad antennas is
obtained from the exoplanet pipeline of the OVRO-LWA. I have tweaked it slightly to make it for different data shapes.
> Flag bad antennas

- ovro_lwa_solar_cal.py
1. First will make a very big image with WSCLEAN.
2. Mask out the region where Sun is and then would predict
model visibilities using WSCLEAN
3. Tried to do uvsub; uvsub gave some error; did manually
by reading corrected data and model data.
4. Then do a clean centered on Sun with CASA
5. Have added code to correct the bug in MS
6. All the functionalities can be run automatically now
using the function "pipeline". The calling sequence is
pipeline(solar_ms, calib_ms=calib_ms) , if bandpass table is absent, and 
calib_ms is the MS from which the calibration solutions would be generated.
if the user wants to use an existing caltable, please supply that
in the optinal parameter bcal.
> Pipeline with WSCLEAN

- solar_pipeline.py
The error was occurring when we are creating the model image using the Gasperin et al. model.
> Correcting for Jy/beam to Jy/pixel

- solar_pipeline.py
Taking care of the fact that if a source has negative image flux, it will not have a scaling_factor key
> Bug in flux_scaling_factor function.

- calibration.py
- deconvolve.py
- examples/test_woody_beam.py
- flux_scaling.py
- primary_beam.py
- selfcal.py
- solar_pipeline.py
- source_subtraction.py
- utils.py
Added fast vis support and some primary beam functions. The fast vis changes are outlined in the commissioning document.
> Fast vis support

- solar_pipeline.py
- test_matrix.txt
- tests/get_tested.py
- utils.py
fast ms in all cases. Issue was being caused by fits format not supporting microseconds.
Small changes in get_tested.py and test_matrix
> Small updates

- calibration.py
- deconvolve.py
- solar_pipeline.py
- utils.py
#18 has been fixed here along with some other small improvements.
> Fixing of issues in Issue 18

- solarpipehost/Dockerfile
- solarpipehost/readme.md
With containers, we can have a more consistent environment to run the pipeline, and also make the method more accessible to everyone, no need to configure the environment from a new machine
> Create docker/singularity container for the pipeline

- .readthedocs.yaml
- docs/Makefile
- docs/conf.py
- docs/index.rst
- docs/make.bat
- docs/requirements.txt
- examples/example_selfcal_grid_run.py
- examples/solar_analysis.py
- examples/solar_analysis_selfcal_with_step.py
- ovrolwasolar/calibration.py
- ovrolwasolar/file_handler.py
- ovrolwasolar/flagging.py
- ovrolwasolar/generate_calibrator_model.py
- ovrolwasolar/primary_beam.py
- ovrolwasolar/selfcal.py
- ovrolwasolar/solar_pipeline.py
- ovrolwasolar/source_subtraction.py
- ovrolwasolar/utils.py
- ovrolwasolar/visualization.py
- solar_realtime_pipeline.py
- tests/get_tested.py
- tests/test_calibrator_model.py
- tests/test_file_handler.py
- tests/test_flux_scaling_class1.py
- tests/test_image_ms_quick.py
- tests/test_primary_beam.py
- tests/test_primary_beam_nivedita_beam.py
- tests/test_woody_beam.py
Examples are updated according to the module's update.
Configured readthedocs and sphinx engine to compile doc automatically from the code comments.
> Update example and doc

- operation/solar_realtime_pipeline.py
Implementation based on @surajit4444mondal's method of calculating a beam flux calibration factor per channel.
> add calculation for beam flux calibration factor

- operation/solar_realtime_pipeline.py
- ovrolwasolar/calibration.py
- ovrolwasolar/deconvolve.py
- ovrolwasolar/flagging.py
- ovrolwasolar/generate_calibrator_model.py
The following feature has been added (modified):
* add an option to save the middle step MS file
* add an option to save the middle step ms files
* use `-horizon-mask 2deg` as default to mitigate horizon direction RFI, which can help a lot in the middle steps
> Feature updates

- ovrolwasolar/uv_sourcemodel.py
Tested speed on calim single node: 4.5s for 12ch * 100time_slot (single subband, 10s)
ovrolwasolar/uv_sourcemodel
> Add feature: fast vis, uv fit model

- ovrolwasolar/visualization.py
logo image embedded in code (as base64)
> Add logo, update realtime pipeline image plot

- README.md
- ovrolwasolar/visualization.py
- setup.cfg
> version 0.1.1: refraction correction tested through realtime pipeline

- ovrolwasolar/refraction_correction.py
`level 1.5` shifted and corrected image, `CRVAL1=0` and `CRVAL2=0`, px, py in header.
In realtime pipeline, we can maintain one csv file per day with following format
| Time stamp          | px0 | px1 | py0 | py1 |
|---------------------|-----|-----|-----|-----|
| 2024-03-21 11:07:37 | 1   | 2   | 3   | 4   |
| ...                 | ..  | ..  | ..  | ..  |
|                     |     |     |     |     |
> Functions for level 1.5 fits file

- ovrolwasolar/refraction_correction.py
Refactor `save_resample_align` to use `ndfits.update` for enhanced compatibility with compressed FITS files.
> Refactor `save_resample_align` to use `ndfits.update` for enhanced compatibility with compressed FITS files.

- ovrolwasolar/h5_adaptpix_fits.py
The recovered fits file passed the test of the plotting function.
> function for compressing

- ovrolwasolar/refraction_correction.py
- ovrolwasolar/visualization.py
Input is the standard FITS file made by suncasa.dspec.
> Add spectrogram plot to visualization

- ovrolwasolar/deconvolve.py
- ovrolwasolar/solar_pipeline.py
- ovrolwasolar/utils.py
following updates:
* adding `-quiet` as default parameter to wsclean
* remove function redundancy, `rename_images` and `get_fast_vis_images` only used for fast image name collection
> minor updates

- ovrolwasolar/solar_pipeline.py
- ovrolwasolar/source_subtraction.py
- ovrolwasolar/utils.py
> Fast vis source subtraction

- ovrolwasolar/solar_pipeline.py
Split after self-calibration by hand using table toolkit and see if we can stop the error in realtime pipeline.
> Hand split

- ovrolwasolar/utils.py
Updates:
Compression optimized for fast vis fits:
* purge corrupted image (SNR<1.5)
(`purge_corrupted` is False by default)
* limit after compression image size to smaller than the original image
* add consistency check:
```
check_h5_fits_consistency(fits_file, hdf5_file)
```
returns true if the hdf5 file is correct (close enough to the fits).
Example of a relatively quiet time:
> compression update for fastvis

- ovrolwasolar/source_subtraction.py
Implemented following:
1. If A-team sources are significantly far, do what we are doing now. Else go to next point.
2. Locate peak within the box and shrink the subtraction box till it reaches 30arcminutes or when all 4 corners of the box is above some threshold distance from solar centre. Values inside this box is used for subtraction. 
3. All points within 1 degree radii from Sun is set to 0. This is done in an approximate manner, as I do not use the fact that the coordinate system is spherical, not euclidean. What this means that we ignore a larger area from the Sun as the solar elevation decreases. At noon, the distance is almost equal to 1 degree.
> Issue 96 solution

- ovrolwasolar/flagging.py
- ovrolwasolar/solar_pipeline.py
- ovrolwasolar/source_subtraction.py
> Source subtraction strategy

- ovrolwasolar/calibration.py
- ovrolwasolar/deconvolve.py
- ovrolwasolar/selfcal.py
- ovrolwasolar/solar_pipeline.py
- ovrolwasolar/source_subtraction.py
- ovrolwasolar/utils.py
1. I am pretty confident now that the CASA AipsError is thrown by split. We initally thought so, and implemented a manual split, but did not change all the splits used by pipeline to manual split. This has been done now.
2. We put in a default antenna list and names in calibration.py, to eliminate any need of supplying the slow_ms during calibrating fast_vis data. The relevant changes were not made in selfcal.py earlier.
3. A few other small updates
> Timeout issue

- ovrolwasolar/source_subtraction.py
The code has been made more general such that it can work even at night time. Minor changes in general.
> Fix polarised source subtraction

- ovrolwasolar/coords.py
- ovrolwasolar/deconvolve.py
- ovrolwasolar/refraction_correction.py
- ovrolwasolar/selfcal.py
- ovrolwasolar/solar_pipeline.py
- ovrolwasolar/source_subtraction.py
- Drop flagged rows (reduce IO 10-15% and some CPU)
- Use selfcal to src-subtraction (save one round of fullsky wsclean, both CPU and IO)
- Move runtime dir to ramdisk (boost IO)
- Clean up older than 45min file in ramdisk (hopefully will work, need to see how it behave in long term)
- Isolate folder of each task
> Performance feature added

- ovrolwasolar/coords.py
- ovrolwasolar/utils.py
Change the order of operation from 'Crop then rotate' to 'Rotate then crop'
> Patch for nan in hdf

- ovrolwasolar/calibration.py
If bcal was not provided, it will be created during bandpass call, but will not be used subsequently. It has been fixed now.
> Fix calibration issue
